id: A06B80D46
base_file: f4E41.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:51:09.956257
  last_modified_at: 2022-06-17 12:51:09.956260
