id: A06B80D46
base_file: fA545.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:51:09.966716
  last_modified_at: 2022-06-17 12:51:09.966719
