id: A06B80D46
base_file: f9266.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:51:09.964819
  last_modified_at: 2022-06-17 12:51:09.964822
