id: A06B80D46
base_file: f35C2.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:51:09.952419
  last_modified_at: 2022-06-17 12:51:09.952427
