id: A06B80D46
base_file: f8C50.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:51:09.962013
  last_modified_at: 2022-06-17 12:51:09.962015
